// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112154503_CreateTableVillaNumber")]
    partial class CreateTableVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<int>("SqrMeters")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Cucina, bagno, divano, Guspini, Lycamobile, Senigallia, Mandolini, contenziosi, Bullitta, mostarda, Lerdammer, Final Fantasy XV, Morra cinese 2",
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(1845),
                            Details = "Ecce ego, ecce vere ego ipse adsum, amici! Ite, aperiamus. Videamus quid in hac capsa sit, quis sit rex cereali. Bene inquadra, bene inquadra, quia non videtur.\r\n\r\nErgo… Super Mario, Super Mario, quis habet? Tu non. Isti? Uh, legere vix possum… ah ah!\r\nEt videamus—uh, rice krispies caerulei et rubei. Quis habet? Nemo, amici. Isti cum leone? Nemo. Isti? Cheerios cinnamomi. Nemo. O Deus! Lucky Charme. Nemo, amici. Ecce alter! O meum Deum!\r\n\r\nMagnum mercatum fecimus, comparema. Ecce hic! Donuts?! Uh, donuts, ita! Oreo aurea forma familiae, ita! “Novum” scriptum est, ahah! O meum Deum, chips ahoy… Amici, rex cereali, rex cereali!\r\n\r\nNon possum desinere, quia adsunt etiam illi Dora Exploratricis! Non credo, non credo—etiam illi Dorae! Grex, magne comparema, magnae nuntiae! Skuu!",
                            ImageUrl = "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2FKUzORBTuIF4%2Fmaxresdefault.jpg&sp=1762773241T20f5a809ef08e73392b8810aa4df87b204e24a89472826ba586cc256bcddd862",
                            Name = "Gleriona",
                            Occupancy = 5,
                            Rate = 250000.98999999999,
                            SqrMeters = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Cucina, bagno, divano, Guspini, Lycamobile, Senigallia, Mandolini, contenziosi, Bullitta, mostarda, Lerdammer, Final Fantasy XV, Morra cinese 2",
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(1905),
                            Details = "Ecce ego, ecce vere ego ipse adsum, amici! Ite, aperiamus. Videamus quid in hac capsa sit, quis sit rex cereali. Bene inquadra, bene inquadra, quia non videtur.\r\n\r\nErgo… Super Mario, Super Mario, quis habet? Tu non. Isti? Uh, legere vix possum… ah ah!\r\nEt videamus—uh, rice krispies caerulei et rubei. Quis habet? Nemo, amici. Isti cum leone? Nemo. Isti? Cheerios cinnamomi. Nemo. O Deus! Lucky Charme. Nemo, amici. Ecce alter! O meum Deum!\r\n\r\nMagnum mercatum fecimus, comparema. Ecce hic! Donuts?! Uh, donuts, ita! Oreo aurea forma familiae, ita! “Novum” scriptum est, ahah! O meum Deum, chips ahoy… Amici, rex cereali, rex cereali!\r\n\r\nNon possum desinere, quia adsunt etiam illi Dora Exploratricis! Non credo, non credo—etiam illi Dorae! Grex, magne comparema, magnae nuntiae! Skuu!",
                            ImageUrl = "https://i.redd.it/4t1tkl6hq13d1.jpeg",
                            Name = "Super Mesa Boogie",
                            Occupancy = 120,
                            Rate = 6000000.9900000002,
                            SqrMeters = 5500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Cucina, bagno, divano, Guspini, Lycamobile, Senigallia, Mandolini, contenziosi, Bullitta, mostarda, Lerdammer, Final Fantasy XV, Morra cinese 2",
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(1909),
                            Details = "Ecce ego, ecce vere ego ipse adsum, amici! Ite, aperiamus. Videamus quid in hac capsa sit, quis sit rex cereali. Bene inquadra, bene inquadra, quia non videtur.\r\n\r\nErgo… Super Mario, Super Mario, quis habet? Tu non. Isti? Uh, legere vix possum… ah ah!\r\nEt videamus—uh, rice krispies caerulei et rubei. Quis habet? Nemo, amici. Isti cum leone? Nemo. Isti? Cheerios cinnamomi. Nemo. O Deus! Lucky Charme. Nemo, amici. Ecce alter! O meum Deum!\r\n\r\nMagnum mercatum fecimus, comparema. Ecce hic! Donuts?! Uh, donuts, ita! Oreo aurea forma familiae, ita! “Novum” scriptum est, ahah! O meum Deum, chips ahoy… Amici, rex cereali, rex cereali!\r\n\r\nNon possum desinere, quia adsunt etiam illi Dora Exploratricis! Non credo, non credo—etiam illi Dorae! Grex, magne comparema, magnae nuntiae! Skuu!",
                            ImageUrl = "https://i.redd.it/4t1tkl6hq13d1.jpeg",
                            Name = "Mimmo Ultra Instinct",
                            Occupancy = 0,
                            Rate = 1.99,
                            SqrMeters = 5,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Città, prato e altre cose",
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(1912),
                            Details = "Sondrio",
                            ImageUrl = "https://it.wikipedia.org/wiki/Sondrio#/media/File:Sondrio_panorama.jpg",
                            Name = "Sondrio",
                            Occupancy = 21504,
                            Rate = 2.0,
                            SqrMeters = 20880,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Cucina, bagno, divano, Guspini, Lycamobile, Senigallia, Mandolini, contenziosi, Bullitta, mostarda, Lerdammer, Final Fantasy XV, Morra cinese 2",
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(1915),
                            Details = "Ecce ego, ecce vere ego ipse adsum, amici! Ite, aperiamus. Videamus quid in hac capsa sit, quis sit rex cereali. Bene inquadra, bene inquadra, quia non videtur.\r\n\r\nErgo… Super Mario, Super Mario, quis habet? Tu non. Isti? Uh, legere vix possum… ah ah!\r\nEt videamus—uh, rice krispies caerulei et rubei. Quis habet? Nemo, amici. Isti cum leone? Nemo. Isti? Cheerios cinnamomi. Nemo. O Deus! Lucky Charme. Nemo, amici. Ecce alter! O meum Deum!\r\n\r\nMagnum mercatum fecimus, comparema. Ecce hic! Donuts?! Uh, donuts, ita! Oreo aurea forma familiae, ita! “Novum” scriptum est, ahah! O meum Deum, chips ahoy… Amici, rex cereali, rex cereali!\r\n\r\nNon possum desinere, quia adsunt etiam illi Dora Exploratricis! Non credo, non credo—etiam illi Dorae! Grex, magne comparema, magnae nuntiae! Skuu!",
                            ImageUrl = "https://i.redd.it/4t1tkl6hq13d1.jpeg",
                            Name = "Sferionisdiolla",
                            Occupancy = 3,
                            Rate = 600000.0,
                            SqrMeters = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 65472345,
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(2002),
                            SpecialDetails = "On fire",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VillaNo = 45897235,
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(2005),
                            SpecialDetails = "Susanna 8",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VillaNo = 67234783,
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(2008),
                            SpecialDetails = "Subbuteo",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VillaNo = 21982387,
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(2010),
                            SpecialDetails = "Tuple varie e altri collezionabili",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VillaNo = 1155664488,
                            CreatedDate = new DateTime(2025, 11, 12, 15, 45, 3, 506, DateTimeKind.Utc).AddTicks(2012),
                            SpecialDetails = "Highway In The Sky... For Final Rush",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
